net-a-porter-mobile/XCTest-Gherkin

Pod/Core/StringGherkinExtension.swift

Previously discussed [in this closed PR](https://github.com/net-a-porter-mobile/XCTest-Gherkin/pull/15) (was a bit too quick deleting the branch of the previous PR, hence a new PR rather than re-opening the old one).
PR contains 2 commits, each using slightly different methods for the `.uppercaseFirstLetterString` and `.humanReadableString` computed properties, where the latter commit, imho, is to be preferred.

Patch 1 - Re-wrote StringGherkinExtension.swift extensions in native Swift 

---

README.md

This example now should compile and pod name is more Ruby style.

Fix "Step definitions" example in README and improve pod name

---

Pod/Core/XCTestCase+Gherkin.swift

flatMap take an array of optionals and return an array of unwrapped optionals without any nils so ! is unnecessary and Xcode 8.2 reports error

Removed unwrapped optional param from flatMap to fix Xcode 8.2 error

---

Pod/Core/StringGherkinExtension.swift
Pod/Core/XCTestCase+Gherkin.swift
Pod/Native/NativeFeature.swift
Pod/Native/ParseState.swift

Add storage of the current step name and some minor code formatting changes.
Storage of the current step name helps us to get clearer logging on our Jenkins CI.

Add storage of the current step name 

---

.travis.yml
CHANGELOG.md

CocoaPods 1.2.0 is the latest version of CocoaPods. Based on the `Podfile.lock` in the example project, we're using CocoaPods 1.2.0 (https://github.com/net-a-porter-mobile/XCTest-Gherkin/blob/master/Example/Podfile.lock#L18). Makes sense to update the Travis version too.

Update CocoaPods version in .travis.yml

---

.travis.yml

I've noticed that since we updated to Xcode 8.3, Travis is timing out a lot more often (error code 65) on builds in latest iOS. It seems to be a recurring issue: https://github.com/travis-ci/travis-ci/issues/6675. I'm hoping this will help. If it doesn't, we might have to think about other ways of palliating these symptoms: https://github.com/travis-ci/travis-ci/issues/6675#issuecomment-282041416 and creating a radar: https://github.com/travis-ci/travis-ci/issues/6675#issuecomment-261757936 and include:
Tarball from `sudo sysdiagnose -q`
Contents of `~/Library/Logs/CoreSimulator`
xcactivity logs from the test run in `~/Library/Developer/Xcode/DerivedData/<project>/Logs`

Update to iOS 10.3 simulator

---

.travis.yml
Pod/Native/NativeTestCase.swift

This reverts commit f7d59064fe20006077a378b3a1876e8711438e23.
Turns out I'm an idiot (not news for some) -- this reverts the change to remove the `open override class func initialize()` and replace it with a `static let` (which are lazily initialized). Also the effects of the change were completely different than I thought they were, so there's that.
I think @smaljaar's suggestion (https://github.com/net-a-porter-mobile/XCTest-Gherkin/issues/66) of removing NativeTestCase and replacing it with the `NativeRunner` makes sense, and, IMO, makes the public API slightly easier to understand.

Revert "Replace initialize class method"

---

.travis.yml
Pod/Core/ClassHelperMethods.swift

Subtle, and very annoying, bug in `allSubclassesOf`.
If the initial call to objc_getClassList returned fewer classes than were returned from the second call then the buffer was filled to the correct limit (bug 1 - some classes might get randomly missed out) but the loop went from 0 to the larger amount (bug 2 - buffer overrun).
Fixed by allocating the buffer to twice the expected amount. Not that fussed by the inefficiency here, it's deallocated almost immediately afterwards, and isn't going to be a _vast_ allocation anyway.
I've also updated the travis file to work with the Xcode 9 image, with a single job still running xcode 8 until we decide to drop support for it.

Travis xcode 9

---

Example/Tests/Features/ExampleFeatures.swift
Example/Tests/StepDefinitions/SanitySteps.swift
README.md

Update README and add test to show start/end regex anchors removing ambiguity.

---

Pod/Core/StepDefiner.swift
Pod/Core/XCTestCase+Gherkin.swift
Pod/Native/NativeTestCase.swift

It's inconvenient when a test step fails to see failures only where the failure actually happened and not in which step of test it happened. With this change currently executed step, location is stored in state and when failure happens additional failure is recorded at the same location. This way it will be visible what step failed and what exact assert down the way caused it.
Failure in feature file:
Failure in steps definer:

Record additional failures in steps

---

Pod/Core/XCTestCase+Gherkin.swift

Xcode can make automatic screenshots which is very helpful when investigating test failures, but there is no way to control this behavior and it creates a lot of redundant screenshots, i.e. it can create a dozen screenshots just while launching the app (14 in my case, but I guess it can depend on how long it takes to load the app). When running UI tests on cloud CI, i.e. CircleCI that results in a dramatic performance hit when uploading test results. For 17 failed tests it generated more than 3000 screenshots making the size of test results bundle more than 1 GB and adding almost 30 minutes to test runtime to upload these artifacts.
Currently, we are making screenshots manually in a `tearDown` of a base test case class, but that will only leave us a single screenshot which might not be …

Allow automatic screenshots before/after steps and on failures

---

Example/Tests/Features/ExampleFeatures.swift
Example/Tests/StepDefinitions/SanitySteps.swift
Pod/Core/MatchedStringRepresentable.swift
README.md

I found it useful to be able to use complex types in tests descriptions and `Codable` can be easily utilized for that. For that new protocol is introduced.
I.e. I can have a test step that is "I receive push \(notification)" where `notification` is the same DTO that is used by the app.
There is one small caveat for this approach which is an override of `description` property so that `print` will output JSON string.

Introduce CodableMatchedStringRepresentable protocol

---

Example/Pods/Pods.xcodeproj/project.pbxproj
Pod/Core/LevenshteinDistance.swift
Pod/Core/XCTestCase+Gherkin.swift

It might be useful not just to print all step definitions, which can be a lot in large projects, on the event of missing step, but suggest some of them as the most likely match.
Not sure how accurate these suggestions will be in a real life because steps are defined using regular expressions patterns, which are obviously not used when steps are invoked. But should be pretty accurate for cases like typos.
Example:
```
Step definition not found for 'Some value should be between one and 7'
-------------
Defined steps
-------------
...
-------------
Copy paste these steps in a StepDefiner subclass:
-------------
step("Some value should be between one and 7") {XCTAssertTrue(true)}
-------------
Or maybe you meant one of these steps:
-------------
/Some value should be between ([0-9]) and …
```

Print suggested steps when can't find step definition

---

Example/Tests/Features/ExampleFeatures.swift
Example/Tests/StepDefinitions/SanitySteps.swift
Pod/Core/Example.swift
Pod/Core/MatchedStringRepresentable.swift
Pod/Core/StepDefiner.swift
Pod/Core/XCTestCase+Gherkin.swift

This PR adds support for custom types as an example value. It takes advantage of earlier introduced `CodableMatchedStringRepresentable`, so types conforming to this protocol can be used both as example values and step match values. Also, any `MatchedStringRepresentable` type can be used as an example value.
This also adds a method to access current example values. It is useful in case some additional operations on data are needed in outline, i.e.:
```swift
func testNotificationOfSomeType() {
Examples(
["notification_type"],
[NotificationType.missedCall],
...
)
Outline(shouldTerminate: true) {
let notificationType = self.notificationTypeFromExample()
let notification = PushNotificationDTO.appointmentNotification(notificationType, appointmentId: "1")
When("I receive notification …
```

Allow using custom example types and access current example values

---

Pod/Core/StringGherkinExtension.swift

This PR improves test debug name (one that is printed in `steps from ...`).
It's usual to use snake case for test names, so it adds snake case to camel case conversion. Also, it fixes the bug that was resulting in non-letters in test names being separated by spaces.
Before: `testFooBar123` -> `Foo Bar 1 2 3`, `test_foo_bar_123` -> `_foo _bar 1 2 3`
After: `testFooBar123` -> `Foo Bar 123`, `test_foo_bar_123` -> `Foo Bar 123`

Improve test debug name

---

Pod/Core/XCTestCase+Gherkin.swift
Pod/Native/NativeFeature.swift
Pod/Native/NativeRunner.swift
Pod/Native/NativeScenario.swift
Pod/Native/NativeTestCase.swift
Pod/Native/ParseState.swift

The current implementation of feature file parser skips empty lines, tags, and comments, so in result line number of steps may be incorrect. This PR fixes this to allow proper highlighting of failed steps in feature files like it was done for native tests in #106 
Also added highlighting of failed examples in scenario outlines.
Result:

Highlight line in feature file when step fails

---

Pod/Core/Step.swift
Pod/Core/XCTestCase+Gherkin.swift

This can be helpful for some tools to allow a quick jump to step source. Activity logs still use short version with just a file name

Print full path to step source in logs

---

Example/Tests/StringGherkinExtensionTests.swift
Example/XCTest-Gherkin_ExampleUITests/StepDefinitions/UITestStepDefinitions.swift
Pod/Core/PageObject.swift
Pod/Core/StringGherkinExtension.swift

This property was wrongly using `static` attribute instead of `class` that would allow it to be overridden in subclasses. Also now overridden value is not transformed with `humanReadbleString` so that it is more predictable - returning already human readable string results in extra spaces between words (now fixed too)

Fix PageObject name property

---

Example/Pods/Pods.xcodeproj/project.pbxproj
Example/Tests/Features/BackgroundTests.swift
Example/Tests/StepDefinitions/SanitySteps.swift
Example/XCTest-Gherkin.xcodeproj/project.pbxproj
Pod/Core/Background.swift
Pod/Core/Example.swift
Pod/Core/XCTestCase+Gherkin.swift
README.md

They are currently only supported for native feature files but can work quite nice in swift tests too.

Backgrounds for native tests

---

CHANGELOG.md
Example/Tests/Features/ExampleFeatures.swift
Example/Tests/StepDefinitions/SanitySteps.swift
Example/XCTest-Gherkin.xcodeproj/xcshareddata/xcschemes/XCTest-Gherkin-Example.xcscheme
Example/XCTest-Gherkin.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
Pod/Core/StepDefiner.swift
README.md

This is implemented as a simple wrapper around the regular expression version of step to keep the code simple - if there is a need for optimising for performance, this can be done under the hood. However (imho) given we are waiting to the UI to update I don't think our performance issue is going to be here (this statement might be proven wrong in the future).

Add Step overload to allow exact string matches

---

Pod/Core/XCTestCase+Gherkin.swift
Pod/Native/NativeTestCase.swift

Resolves #103
When methods of test case are called from another test they don't have associated invocation.

Fixed accessing invocation property on test methods called directly

---

.travis.yml

I think it should be safe to assume that Xcode 10 and Swift 4 are used by the majority of the library users by this point.

Do not build with xcode 9 on travis

---

Example/Tests/Features/ScenarioContextTests.swift
Example/Tests/StepDefinitions/SanitySteps.swift
Example/XCTest-Gherkin.xcodeproj/project.pbxproj
Pod/Core/XCTestCase+Gherkin.swift

We faced a scenario when running step should return the value that then should be used by another step. Even though it can be solved outside of the framework via global variables this is not a very nice solution. So the framework can offer a better way to do that, i.e. by providing a "userInfo"-like storage in the current test state (as we already keep track of it anyway) and allow interpolating state variables the same way as example variables (though this is not necessary and state value can be used in the steps as their implementation detail)

Add scenario context to the test state

---

Pod/Native/Language.swift

I was trying to make work my localized feature which uses Scenario Outline and I observed that Scenario Outline step is not being parsed. I discovered that it's because of the wrong expression used in Keyword definition.
In `gherkin-languages.json`:
```json
"scenario outline": [
"Структура сценария"
],
```
But in [`Language.swift` (L56)](https://github.com/net-a-porter-mobile/XCTest-Gherkin/blob/master/Pod/Native/Language.swift#L56):
```swift
let ScenarioOutline = Language.current.localized(expression: "scenarioOutline", default: "Scenario Outline", ending: ":")
```
First one uses "scenario outline", second one uses "scenarioOutline". That's why it always falls back to default ("Scenario Outline") - and that's how I made it work for now.

Fix incorrect expression on ScenarioOutline keyword
